-- Delete ARTIST
DELETE FROM DSA_CHINOOK.ARTIST

-- Delete ALBUM
DELETE FROM DSA_CHINOOK.ALBUM

-- Delete TRACK
DELETE FROM DSA_CHINOOK.TRACK

-- Delete CUSTOMER
DELETE FROM DSA_CHINOOK.CUSTOMER

-- Delete EMPLOYEE
DELETE FROM DSA_CHINOOK.EMPLOYEE

-- Delete INVOICE
DELETE FROM DSA_CHINOOK.INVOICE

-- Delete INVOICELINE
DELETE FROM DSA_CHINOOK.INVOICELINE

-- Delete PLAYLIST
DELETE FROM DSA_CHINOOK.PLAYLIST

-- Delete GENRE
DELETE FROM DSA_CHINOOK.GENRE

-- Delete MEDIATYPE
DELETE FROM DSA_CHINOOK.MEDIATYPE

-- Delete PLAYLISTTRACK
DELETE FROM DSA_CHINOOK.PLAYLISTTRACK

