chinook_dbt:
  outputs:
    dev:
      dbname: chinook
      host: postgres
      pass: chinook
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: chinook
  target: dev

elementary:
  outputs:
    default:
      dbname: chinook
      host: postgres
      pass: chinook
      port: 5432
      schema: elementary
      threads: 1
      type: postgres
      user: chinook
  target: default


