-- Clean PLAYLISTTRACK
DELETE FROM ODS_CHINOOK.PLAYLISTTRACK a
WHERE (a.PLAYLISTID, a.TRACKID) IN (SELECT s.PLAYLISTID, s.TRACKID FROM DSA_CHINOOK.PLAYLISTTRACK s)

-- Clean ARTIST
DELETE FROM ODS_CHINOOK.ARTIST
WHERE ArtistId IN (SELECT ArtistId FROM DSA_CHINOOK.ARTIST)

-- Clean ALBUM
DELETE FROM ODS_CHINOOK.ALBUM
WHERE AlbumId IN (SELECT AlbumId FROM DSA_CHINOOK.ALBUM)

-- Clean TRACK
DELETE FROM ODS_CHINOOK.TRACK
WHERE TrackId IN (SELECT TrackId FROM DSA_CHINOOK.TRACK)

-- Clean CUSTOMER
DELETE FROM ODS_CHINOOK.CUSTOMER
WHERE CustomerId IN (SELECT CustomerId FROM DSA_CHINOOK.CUSTOMER)

-- Clean EMPLOYEE
DELETE FROM ODS_CHINOOK.EMPLOYEE
WHERE EmployeeId IN (SELECT EmployeeId FROM DSA_CHINOOK.EMPLOYEE)

-- Clean INVOICE
DELETE FROM ODS_CHINOOK.INVOICE
WHERE InvoiceId IN (SELECT InvoiceId FROM DSA_CHINOOK.INVOICE)

-- Clean INVOICELINE
DELETE FROM ODS_CHINOOK.INVOICELINE
WHERE InvoiceLineId IN (SELECT InvoiceLineId FROM DSA_CHINOOK.INVOICELINE)

-- Clean PLAYLIST
DELETE FROM ODS_CHINOOK.PLAYLIST
WHERE PlaylistId IN (SELECT PlaylistId FROM DSA_CHINOOK.PLAYLIST)

-- Clean GENRE
DELETE FROM ODS_CHINOOK.GENRE
WHERE GenreId IN (SELECT GenreId FROM DSA_CHINOOK.GENRE)

-- Clean MEDIATYPE
DELETE FROM ODS_CHINOOK.MEDIATYPE
WHERE MediaTypeId IN (SELECT MediaTypeId FROM DSA_CHINOOK.MEDIATYPE)
